"""initial schema: movie, person, genre, movie_genre, credit

Revision ID: 5c83582a2064
Revises: 
Create Date: 2026-07-26 18:26:00.258114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c83582a2064'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit', 'character_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_credit_movie_id'), table_name='credit')
    op.drop_index(op.f('idx_credit_person_id'), table_name='credit')
    op.create_index('ix_credit_movie_id', 'credit', ['movie_id'], unique=False)
    op.create_index('ix_credit_person_id', 'credit', ['person_id'], unique=False)
    op.alter_column('movie', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('person', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('movie', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('ix_credit_person_id', table_name='credit')
    op.drop_index('ix_credit_movie_id', table_name='credit')
    op.create_index(op.f('idx_credit_person_id'), 'credit', ['person_id'], unique=False)
    op.create_index(op.f('idx_credit_movie_id'), 'credit', ['movie_id'], unique=False)
    op.alter_column('credit', 'character_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
